name: Notify Website

on:
  push:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger website rebuild
        uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697 # v4.0.1
        with:
          token: ${{ secrets.WEBSITE_DISPATCH_TOKEN }}
          repository: PhillipChaffee/phillipchaffee.github.io
          event-type: resume-updated
